
#.ONESHELL

all:
		cd build && voc -s ../lists/Sys.Mod \
		../lists/strutils.Mod \
		../lists/List.Mod \
		../lists/StringList.Mod \
		../postgres/postgres.Mod \
		../pipes/pipes.Mod \
		../d2h.Mod -m

clean:
		cd build && rm *
